@startuml
title 	块存储增量同步数据采集

actor user
participant "定时任务" as A
participant "BOMC接口采集处理模块" as B
participant "文件服务器模块" as C



activate A

A   -> B:接收块存储增量同步数据采集请求
activate B

B   -> C:读取块存储增量同步数据
activate C

C --> B:返回读取块存储增量同步数据结果
deactivate



B   -> C:将原始目录下的块存储增量同步数据写入到校验目录下
activate C

C --> B:返回写入结果
deactivate
B   -> B:记录操作信息



B --> A:返回块存储增量同步数据采集结果
A -> B:返回块存储增量同步数据采集结果

@enduml