@startuml

actor user
participant "定时任务" as A
participant "BOMC接口采集处理模块" as B
participant "文件服务器模块" as C

activate A

Alice -> Bob: Authentication Request
Alice -> test2:fast
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml