@startuml
Alice -> Bob: Authentication Request
Alice -> test2:fast
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml