@startuml
title 	服务系统日志采集


participant "定时任务" as A
participant "服务系统日志采集" as B
participant "服务服务系统日志" as C
participant "消息队列" as D


activate A


A   -> B:接收日志采集请求
activate B

B   -> C:读取日志
activate C

C -> D:写入消息队列
activate D

D -> C:返回写入结果
C -> B:返回写入结果
B -> A:返回写入结果

@enduml