@startuml
title 	采集系统数据的日志清洗


participant "定时任务" as A
participant "采集系统日志清洗" as B
participant "消息队列" as D


activate A


A   -> B:接收日志采集请求
activate B

B   -> D:读取日志
activate D

D -> B:返回写入结果
B -> A:返回写入结果

@enduml