@startuml
title 	采集日志入库


participant "定时任务" as A
participant "采集消息队列" as B
participant "数据库" as D


activate A


A   -> B:接收日志清洗更新请求
activate B

B   -> D:持久化数据到数据库
activate D

D -> B:返回写入结果
B -> A:返回写入结果

@enduml