@startuml
title 	告警合并规则变更修改


participant "定时任务" as A
participant "用户信息校验" as B
participant "消息队列" as D


activate A


A   -> B:接收日志采集请求
activate B

B   -> D:读取日志
activate D

D -> B:返回写入结果
B -> A:返回写入结果

@enduml