
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2020-1-4'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2020-1-3'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2020-1-2'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2020-1-1'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-31'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-30'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-29'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-28'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-27'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-26'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-25'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-24'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-23'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-22'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-21'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;
insert into midata.mi_action_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    customer_name ,    device_uuid ,    action_type ,    action_name ,    view_name ,    ch_start_date ,    timestamp ,    duration ,    error_count ,    slow_count ,    total_count ,    bytes_sent ,    bytes_received) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      customer_name,      device_uuid,      action_type,      action_name,      view_name,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      countIfState(http_error_count > 0) AS error_count,      sumState(is_slow) AS slow_count,      countState() AS total_count,      sumState(http_bytes_sent) AS bytes_sent,      sumState(http_bytes_received) AS bytes_received FROM midata.mi_action_local 
 where ch_start_date='2019-12-20'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, action_type, action_name, view_name, ch_start_date, timestamp;

