
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2020-1-4'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2020-1-3'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2020-1-2'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2020-1-1'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-31'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-30'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-29'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-28'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-27'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-26'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-25'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-24'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-23'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-22'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-21'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local 
 where ch_start_date='2019-12-20'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;

