
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2020-1-4';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2020-1-3';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2020-1-2';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2020-1-1';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-31';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-30';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-29';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-28';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-27';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-26';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-25';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-24';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-23';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-22';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-21';
insert into webviewdata.web_js_error_local (  app_id ,  app_version_id ,  visit_id ,  action_id ,  agent_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  carrier_id ,  browser_id ,  page_url ,  iframe_status ,  exception_class ,  request_uri ,  message ,  browser_stack_hash ,  request_referer ,  browser_name ,  timestamp ,  ch_start_date  ) SELECT app_id,            app_version_id,            visit_id,            action_id,            agent_id,            os_id,            device_id,            country_id,            region_id,            city_id,            carrier_id,            browser_id,            page_url,            iframe_status,            exception_class,            request_uri,            message,            browser_stack_hash,            request_referer,            browser_name,            timestamp,            ch_start_date    FROM webviewdata.`.inner.web_js_error_local_bak_1108`    
 where ch_start_date='2019-12-20';

