
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2020-1-4';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2020-1-3';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2020-1-2';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2020-1-1';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-31';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-30';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-29';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-28';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-27';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-26';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-25';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-24';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-23';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-22';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-21';
insert into  midata.anr_local (    uuid ,    app_id ,    app_version_id ,    agent_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    visit_id ,    customer_name ,    device_uuid ,    occur_package ,    occur_location ,    message ,    description ,    mobile_app_name ,    anr_thread ,    other_threads ,    trace ,    cpu ,    memory ,    memory_available ,    hard_disk ,    root ,    visit_start_time ,    anr_time ,    timestamp ,    ch_start_date) SELECT      uuid,      app_id,      app_version_id,      agent_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      visit_id,      customer_name,      device_uuid,      occur_package,      occur_location,      message,      description,      mobile_app_name,      anr_thread,      other_threads,      trace,      cpu,      memory,      memory_available,      hard_disk,      root,      visit_start_time,      anr_time,      timestamp,      ch_start_date FROM midata.`.inner.anr_local_bak_1108` 
 where ch_start_date='2019-12-20';

