@startuml
title 告警合并规则变更删除管理

actor user
participant "告警合并规则变更删除管理页面展示" as A
participant "告警合并规则变更删除管理模块" as B
participant "数据库模块" as C

user  -> A:点击保存按钮
activate A
A   -> B:发送接收告警合并规则关联应用类资源性能采集数据请求
activate B
B   -> B:校验校验告警合并规则关联应用类资源性能采集数据请求头的合法性
activate C
B   -> C:告警合并规则关联应用类资源性能采集数据入库
C --> B:返回告警合并规则关联应用类资源性能采集数据入库结果

A   -> B:发送告警合并规则关联业务类资源性能采集数据请求
B   -> B:校验告警合并规则关联业务类资源性能采集数据请求头的合法性
B   -> C:告警合并规则关联业务类资源性能采集数据入库
C --> B:返回告警合并规则关联业务类资源性能采集数据入库结果

A   -> B:发送接收告警合并规则关联逻辑类资源性能采集数据请求
B   -> B:校验告警合并规则关联逻辑类资源性能采集数据请求头的合法性
B   -> C:告警合并规则关联逻辑类资源性能采集数据入库
C --> B:返回告警合并规则关联逻辑类资源性能采集数据入库结果

A   -> B:发送告警合并规则关联物理类资源性能采集数据请求
B   -> B:校验告警合并规则关联物理类资源性能采集数据请求头的合法性
B   -> C:告警合并规则关联物理类资源性能采集数据入库
C --> B:返回告警合并规则关联物理类资源性能采集数据入库结果

A   -> B:发送告警合并规则关联其他类资源性能采集数据请求
B   -> B:校验告警合并规则关联其他类资源性能采集数据请求头的合法性
B   -> C:告警合并规则关联其他类资源性能采集数据入库
C --> B:返回告警合并规则关联其他类资源性能采集数据结果

A   -> B:发送告警合并规则状态（生失效）变更请求
B   -> B:校验校验告警合并规则状态（生失效）变更请求头的合法性
B   -> C:告警告警告警合并规则状态（生失效）变更库
C --> B:返回告警合并规则状态（生失效）变更入库结果


B   --> A:返回保存告警合并规则变更删除管理结果信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击告警合并规则删除按钮
activate A
A   -> B:发送告警合并规则删除的请求
activate B
B   -> B:校验告警合并规则删除请求头的合法性
activate C
B   -> C:删除告警合并规则
C --> B:返回告警合并规则删除结果返回值

B   --> A:返回告警合并规则删除结果返回值
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击告警合并规则批量删除按钮
activate A
A   -> B:发送告警合并规则批量删除的请求
activate B
B   -> B:校验告警合并规则批量删除请求头的合法性
activate C
B   -> C:批量删除告警合并规则
C --> B:返回告警合并规则批量删除结果返回值

B   --> A:返回告警合并规则批量删除结果返回值
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击告警合并规则全量同步
activate A
A   -> B:发送告警合并规则全量同步请求
activate B
B   -> B:校验告警合并规则全量同步请求头的合法性
activate C
B   -> C:全量同步告警合并规则
C --> B:返回告警合并规则全量同步结果返回值

B   --> A:返回告警合并规则全量同步结果返回值
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击页面功能模块
activate A
A   -> B:发送备份告警合并规则日志请求
activate B
B   -> B:校验校验备份告警合并规则日志请求头的合法性
activate C
B   -> C:备份告警合并规则日志
C --> B:返回告警合并规则全量同步结果返回值

B   --> A:返回备份告警合并规则日志结果返回值
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

@enduml