@startuml
title 告警合并规则新增管理



actor user
participant "告警合并规则新增管理页面展示" as A
participant "告警合并规则新增管理模块" as B
participant "数据库模块" as C

user  -> A:点击查询按钮
activate A
A   -> B:查询展示告警合并规则列表信息
activate B
B   -> B:校验告警合并规则列表请求头的合法性
activate C
B   -> C:查询展示告警合并规则列表信息
C --> B:返回查询展示告警合并规则列表信息

A   -> B:发送告警合并规则展示请求
B   -> B:校验告警合并规则列表请求头的合法性
B   -> C:查询展示告警合并规则列表信息
C --> B:返回查询展示告警合并规则列表信息

A   -> B:发送告警合并规则查询请求
B   -> B:校验告警合并规则查询请求头的合法性
B   -> C:查询告警合并规则列表信息
C --> B:返回查询告警合并规则信息

A   -> B:发送告警合并规则按照资源模型查询请求
B   -> B:校验告警合并规则按照资源模型查询请求头的合法性
B   -> C:查询告警合并规则按照资源模型信息
C --> B:返回告警合并规则按照资源模型信息

A   -> B:发送告警合并规则详情查看请求
B   -> B:校验告警合并规则详情查看请求头的合法性
B   -> C:查看告警合并规则详情信息信息
C --> B:返回告警合并规则详情查看信息

B   --> A:返回查询的结果信息
A   --> user:展示给用户相关信息

deactivate A
deactivate B
deactivate C

user  -> A:点击告警合并规则新增按钮
activate A
activate B
A   -> B:发送新增告警合并规则字段的请求
B   -> B:校验新增告警合并规则字段请求头的合法性
activate C
B   -> C:告警合并规则新增字段
C --> B:返回新增告警合并规则字段结果返回值
B --> A:返回新增告警合并规则字段结果返回值
A --> user:返回新增告警合并规则字段结果返回值

deactivate A
deactivate B
deactivate C

user  -> A:点击告警合并按照资源类型合并按钮
activate A
activate B
A   -> B:发送合并应用类资源告警规则的请求
B   -> B:校验合并应用类资源告警规则请求头的合法性
activate C
B   -> C:合并应用类资源告警规则
C --> B:返回合并应用类资源告警规则结果返回值

A   -> B:发送应用类资源包含子路径告警合并规则的请求
B   -> B:校验应用类资源包含子路径告警合并规则请求头的合法性
B   -> C:合并应用类资源包含子路径告警规则
C --> B:返回合并应用类资源包含子路径告警规则结果返回值

A   -> B:发送业务类资源告警合并规则的请求
B   -> B:校验校验业务类资源告警合并规则请求头的合法性
B   -> C:合并合并业务类资源告警规则
C --> B:返回业务类资源告警合并规则结果返回值

A   -> B:发送业务类资源包含子路径告警合并规则的请求
B   -> B:校验业务类资源包含子路径告警合并规则请求头的合法性
B   -> C:合并业务类资源包含子路径告警规则
C --> B:返回业务类资源包含子路径告警合并规则结果返回值


A   -> B:发送合并逻辑类资源告警规则的请求
B   -> B:校验合并逻辑类资源告警规则请求头的合法性
B   -> C:合并逻辑类资源告警规则
C --> B:返回合并逻辑类资源告警规则结果返回值

A   -> B:发送合并物理类资源告警规则的请求
B   -> B:校验合并物理类资源告警规则请求头的合法性
B   -> C:合并物理类资源告警规则
C --> B:返回合并物理类资源告警规则结果返回值

A   -> B:发送合并物理类资源包含子路径告警规则的请求
B   -> B:校验合并物理类资源包含子路径告警规则请求头的合法性
B   -> C:合并物理类资源包含子路径告警规则
C --> B:返回合并物理类资源包含子路径告警规则结果返回值

A   -> B:发送合并其他类资源告警规则的请求
B   -> B:校验合并其他类资源告警规则请求头的合法性
B   -> C:合并其他类资源告警规则
C --> B:返回合并其他类资源告警规则结果返回值

A   -> B:发送合并其他类资源含子路径告警规则的请求
B   -> B:校验合并其他类资源含子路径告警规则请求头的合法性
B   -> C:合并其他类资源含子路径告警规则
C --> B:返回合并其他类资源含子路径告警规则结果返回值

B --> A:返回用户合并的操作结果
A --> user:返回用户合并的操作结果

deactivate A
deactivate B
deactivate C

user  -> A:用户设置合并周期
activate A
activate B
A   -> B:发送设置合并周期的请求
B   -> B:校验设置合并周期请求头的合法性
activate C
B   -> C:设置合并周期时间
C --> B:返回设置合并周期结果返回值
B --> A:返回设置合并周期结果返回值
A --> user:返回设置合并周期结果返回值

deactivate A
deactivate B
deactivate C

@enduml