@startuml
title 告警自动归并规则管理



actor user
participant "告警自动归并规则管理页面展示" as A
participant "告警自动归并规则管理模块" as B
participant "数据库模块" as C

user  -> A:点击查询按钮
activate A
A   -> B:发送告警自动归并规则列表展示请求
activate B
B   -> B:校验告警自动归并规则列表展示头的合法性
activate C
B   -> C:展示告警自动归并规则列表
C --> B:返回告警自动归并规则列表展示信息

A   -> B:发送收告警自动归并规则查询请求
B   -> B:校验告警自动归并规则查询请求头的合法性
B   -> C:查询告警自动归并规则
C --> B:返回查询告警自动归并规则信息

A   -> B:发送告警自动归并规则详情查看的请求
B   -> B:校验告警自动归并规则详情查看请求头的合法性
B   -> C:查询查看告警自动归并规则详情
C --> B:返回告警自动归并规则详情查看信息
B   --> A:返回查询的结果信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C


user  -> A:点击查询按钮
activate A
A   -> B:发送新增告警自动归并规则字段的请求
activate B
B   -> B:校验新增告警自动归并规则字段请求头的合法性
activate C
B   -> C:新增告警自动归并规则字段信息
C --> B:返回新增告警自动归并规则字段结果信息

A   -> B:发送主从告警归并规则关联应用类资源告警指标的请求
B   -> B:校验校验主从告警归并规则关联应用类资源告警指标请求头的合法性
B   -> C:主从告警归并规则关联应用类资源告警指标信息
C --> B:返回主从告警归并规则关联应用类资源告警指标结果信息

A   -> B:发送主从告警归并规则关联业务类资源告警指标的请求
B   -> B:校验主从告警归并规则关联业务类资源告警指标请求头的合法性
B   -> C:主从告警归并规则关联业务类资源告警指标信息
C --> B:返回主从告警归并规则关联业务类资源告警指标结果信息

A   -> B:发送主从告警归并规则关联逻辑类资源告警指标的请求
B   -> B:校验主从告警归并规则关联逻辑类资源告警指标请求头的合法性
B   -> C:主从告警归并规则关联逻辑类资源告警指标信息
C --> B:返回主从告警归并规则关联逻辑类资源告警指标结果信息

A   -> B:发送主从告警归并规则关联物理类资源告警指标的请求
B   -> B:校验主从告警归并规则关联物理类资源告警指标请求头的合法性
B   -> C:主从告警归并规则关联物理类资源告警指标信息
C --> B:返回主从告警归并规则关联物理类资源告警指标结果信息

A   -> B:发送主从告警归并规则关联其他类资源告警指标的请求
B   -> B:校验主从告警归并规则关联其他类资源告警指标请求头的合法性
B   -> C:主从告警归并规则关联其他类资源告警指标信息
C --> B:返回主从告警归并规则关联其他类资源告警指标结果信息

A   -> B:发送告警自动归并规则关联状态的请求
B   -> B:校验告警自动归并规则关联状态请求头的合法性
B   -> C:新增告警自动归并规则关联状态信息
C --> B:返回告警自动归并规则关联状态结果信息

B   --> A:返回新增告警指标的的结果信息
A   --> user:展示新增告警指标的的结果信息
deactivate A
deactivate B
deactivate C

user  -> A:点击告警自动归并规则修改按钮
activate A
A   -> B:发送告警自动归并规则删除请求
activate B
B   -> B:校验告警自动归并规则删除请求头的合法性
activate C
B   -> C:删除告警自动归并规则
C --> B:返回告警自动归并规则删除结果返回值

A   -> B:发送告警自动归并规则批量删除请求
B   -> B:校验告警自动归并规则批量删除请求头的合法性
B   -> C:批量删除告警自动归并规则
C --> B:返回告警自动归并规则批量删除结果返回值

A   -> B:发送告警自动归并规则批删除请求
B   -> B:校验告警自动归并规则全量同步请求头的合法性
B   -> C:全量同步告警自动归并规则
C --> B:返回告警自动归并规则全量同步结果返回值

A   -> B:发送告警自动归并规则日志记录请求
B   -> B:校验告警自动归并规则日志记录请求头的合法性
B   -> C:自动归并告警规则日志记录
C --> B:返回告警自动归并规则日志记录结果返回值

B   --> A:返回告警自动归并规则修改结果信息
A   --> user:展示告警自动归并规则修改结果信息
deactivate A
deactivate B
deactivate C


@enduml