@startuml
title 资源子模型管理

actor user
participant "资源子模型管理页面展示" as A
participant "资源子模型管理模块" as B
participant "数据库模块" as C

user  -> A:点击资源子模型管理页面展示按钮
activate A
A   -> B:发送资源子模型展示的请求
activate B
B   -> B:校验资源子模型展示的请求头的合法性
activate C
B   -> C:查询资源子模型信息
C --> B:展示资源子模型列表信息

A   -> B:发送资源子模型统计图展示的请求
B   -> B:校验资源子模型统计图展示的请求头的合法性
B   -> C:查询资源子模型统计图信息
C --> B:返回查询展示资源子模型统计图信息

B   --> A:返回资源子模型展示信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击资源子模型新增按钮
activate A
A   -> B:发送应用资源子模型导入及模板下载请求
activate B
B   -> B:校验应用资源子模型导入及模板下载请求头的合法性
activate C
B   -> C:数据库导出应用资源子模型导入及模板文件
C --> B:返回导出应用资源子模型导入及模板文件结果

A   -> B:发送业务资源子模型导入及模板下载请求
B   -> B:校验业务资源子模型导入及模板下载请求头的合法性
B   -> C:数据库导出业务资源子模型导入及模板文件
C --> B:返回导出业务资源子模型导入及模板文件结果

A   -> B:发送逻辑资源子模型导入及模板下载请求
B   -> B:校验逻辑资源子模型导入及模板下载请求头的合法性
B   -> C:数据库导出逻辑资源子模型导入及模板文件
C --> B:返回导出逻辑资源子模型导入及模板文件结果

A   -> B:发送物理资源子模型导入及模板下载请求
B   -> B:校验物理资源子模型导入及模板下载请求头的合法性
B   -> C:数据库导出物理资源子模型导入及模板文件
C --> B:返回导出物理资源子模型导入及模板文件结果

A   -> B:发送其他资源子模型导入及模板下载请求
B   -> B:校验其他资源子模型导入及模板下载请求头的合法性
B   -> C:数据库导出其他资源子模型导入及模板文件
C --> B:返回导出其他资源子模型导入及模板文件结果

B   --> A:返回资源子模型新增结果信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C


user  -> A:点击资源子模型字段变更规则按钮
activate A
A   -> B:发送资源子模型ID和名称定义请求
activate B
B   -> B:校验资源子模型ID和名称定义请求头的合法性
activate C
B   -> C:定义资源子模型ID和名称入库
C --> B:返回资源子模型ID和名称定义结果

A   -> B:发送资源子模型归类定义请求
B   -> B:校验资源子模型归类定义请求头的合法性
B   -> C:禁用/启用资源子模型规则
C --> B:返回合并应用类资源告警规则结果返回值

A   -> B:发送资源子模型启用规则的请求
B   -> B:校验资源子模型启用规则的请求头的合法性
B   -> C:定义资源子模型归类
C --> B:返回资源子模型归类定义结果

A   -> B:发送接收云模型定义请求
B   -> B:校验云模型定义请求头的合法性
B   -> C:定义云模型入库
C --> B:返回云模型定义结果

A   -> B:发送是否监控定义请求
B   -> B:校验是否监控定义请求头的合法性
B   -> C:定义是否监控
C --> B:返回是否监控定义结果

A   -> B:发送采集类型定义请求
B   -> B:校验采集类型定义请求头的合法性
B   -> C:定义采集类型
C --> B:返回采集类型定义结果

A   -> B:发送属性列表定义请求
B   -> B:校验属性列表定义请求头的合法性
B   -> C:定义属性列表入库
C --> B:返回属性列表定义结果

B   --> A:返回资源子模型字段变更规则信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击自定义模型表单按钮
activate A
A   -> B:发送自定义模型表单的请求
activate B
B   -> B:校验自定义模型表单请求头的合法性
activate C
B   -> C:保存自定义模型表单
C --> B:返回保存自定义模型表单结果

B   --> A:返回保存自定义模型表单结果
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击修改资源子模型按钮
activate A
A   -> B:发送修改资源子模型的请求
activate B
B   -> B:校验修改资源子模型请求头的合法性
activate C
B   -> C:修改后资源子模型信息后入库
C --> B:返回修改资源子模型信息后入库结果

B   --> A:返回修改资源子模型信息后入库结果
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击删除资源子模型按钮
activate A
A   -> B:发送删除资源子模型的请求
activate B
B   -> B:校验删除资源子模型请求头的合法性
activate C
B   -> C:删除后的资源子模型信息后入库
C --> B:返回删除后的资源子模型信息后入库结果

B   --> A:返回删除后的资源子模型信息后入库结果
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击资源子模型页面按钮
activate A
A   -> B:发送记录资源子模型日志的请求
activate B
B   -> B:校验资源子模型日志的请求头的合法性
activate C
B   -> C:记录资源子模型的日志入库
C --> B:返回记录资源子模型的日志入库返回值

B   --> A:返回记录资源子模型的日志入库返回值
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

@enduml