@startuml
title 资源数据新增管理

actor user
participant "资源数据新增管理页面展示" as A
participant "资源数据新增管理模块" as B
participant "数据库模块" as C

user  -> A:点击资源属性关键字查询按钮
activate A
A   -> B:发送资源属性关键字查询的请求
activate B
B   -> B:校验资源属性关键字查询请求头的合法性
activate C
B   -> C:从数据库中查询资源属性关键字信息
C --> B:返回资源属性关键字查询的结果信息

A   -> B:发送资源id/名称查询的请求
B   -> B:校验校验资源id/名称查询请求头的合法性
B   -> C:从数据库中查询资源id/名称信息
C --> B:返回资源id/名称查询的结果信息

A   -> B:发送资源监控情况查询的请求
B   -> B:校验资源监控情况查询请求头的合法性
B   -> C:从数据库中查询资源监控情况信息
C --> B:返回资源监控情况查询的结果信息

B   --> A:返回资源数据查询信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击应用类资源数据展示按钮
activate A
A   -> B:发送应用类资源数据查询的请求
activate B
B   -> B:校验应用类资源数据查询请求头的合法性
activate C
B   -> C:从数据库中查询应用类资源数据信息
C --> B:返回应用类资源数据查询的结果信息

A   -> B:发送应用类资源数据详情查询的请求
B   -> B:校验应用类资源数据详情查询请求头的合法性
B   -> C:从数据库中查询应用类资源数据详情信息
C --> B:返回应用类资源数据详情查询的结果信息

A   -> B:发送应用类资源数据保存草稿的请求
B   -> B:校验应用类资源数据保存草稿的请求头的合法性
B   -> C:把应用类资源数据保存草稿内容写入数据库
C --> B:返回应用类资源数据保存草稿内容入库的结果信息

A   -> B:发送应用类资源数据提交审批的请求
B   -> B:校验应用类资源数据提交审批的请求头的合法性
B   -> C:把应用类资源数据提交审批内容写入数据库
C --> B:返回应用类资源数据提交审批内容入库的结果信息

A   -> B:发送应用类资源数据导入/模板下载的请求
B   -> B:校验应用类资源数据导入/模板下载的请求头的合法性
B   -> C:把应用类资源数据导入/模板下载内容写入数据库
C --> B:返回应用类资源数据导入/模板下载内容入库的结果信息

B   --> A:返回应用类资源数据信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击业务类资源数据变更按钮
activate A
A   -> B:发送业务类资源数据查询的请求
activate B
B   -> B:校验业务类资源数据查询请求头的合法性
activate C
B   -> C:从数据库中查询业务类资源数据信息
C --> B:返回业务类资源数据查询的结果信息

A   -> B:发送业务类资源数据详情查询的请求
B   -> B:校验业务类资源数据详情查询请求头的合法性
B   -> C:从数据库中查询业务类资源数据详情信息
C --> B:返回业务类资源数据保存草稿内容入库的结果信息

A   -> B:发送业务类资源数据保存草稿的请求
B   -> B:校验业务类资源数据保存草稿的请求头的合法性
B   -> C:把业务类资源数据保存草稿内容写入数据库
C --> B:返回业务类资源数据详情查询的结果信息

A   -> B:发送业务类资源数据提交审批的请求
B   -> B:校验业务类资源数据提交审批的请求头的合法性
B   -> C:把业务类资源数据提交审批内容写入数据库
C --> B:返回业务类资源数据提交审批内容入库的结果信息

B   --> A:返回业务类资源数据提交审批内容入库的结果信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击逻辑类资源数据变更按钮
activate A
A   -> B:发送逻辑类资源数据查询的请求
activate B
B   -> B:校验逻辑类资源数据查询请求头的合法性
activate C
B   -> C:从数据库中查询逻辑类资源数据信息
C --> B:返回逻辑类资源数据查询的结果信息

A   -> B:发送逻辑类资源数据详情查询的请求
B   -> B:校验逻辑类资源数据详情查询请求头的合法性
B   -> C:从数据库中查询逻辑类资源数据详情信息
C --> B:返回逻辑类资源数据保存草稿内容入库的结果信息

A   -> B:发送逻辑类资源数据保存草稿的请求
B   -> B:校验逻辑类资源数据保存草稿的请求头的合法性
B   -> C:把逻辑类资源数据保存草稿内容写入数据库
C --> B:返回逻辑类资源数据详情查询的结果信息

A   -> B:发送逻辑类资源数据提交审批的请求
B   -> B:校验逻辑类资源数据提交审批的请求头的合法性
B   -> C:把逻辑类资源数据提交审批内容写入数据库
C --> B:返回逻辑类资源数据提交审批内容入库的结果信息

B   --> A:返回逻辑类资源数据提交审批内容入库的结果信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击物理类资源数据变更按钮
activate A
A   -> B:发送物理类资源数据查询的请求
activate B
B   -> B:校验物理类资源数据查询请求头的合法性
activate C
B   -> C:从数据库中查询物理类资源数据信息
C --> B:返回物理类资源数据查询的结果信息

A   -> B:发送物理类资源数据详情查询的请求
B   -> B:校验物理类资源数据详情查询请求头的合法性
B   -> C:从数据库中查询物理类资源数据详情信息
C --> B:返回物理类资源数据保存草稿内容入库的结果信息

A   -> B:发送物理类资源数据保存草稿的请求
B   -> B:校验物理类资源数据保存草稿的请求头的合法性
B   -> C:把物理类资源数据保存草稿内容写入数据库
C --> B:返回物理类资源数据详情查询的结果信息

A   -> B:发送物理类资源数据提交审批的请求
B   -> B:校验物理类资源数据提交审批的请求头的合法性
B   -> C:把物理类资源数据提交审批内容写入数据库
C --> B:返回物理类资源数据提交审批内容入库的结果信息

B   --> A:返回物理类资源数据提交审批内容入库的结果信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

user  -> A:点击其他类资源数据变更按钮
activate A
A   -> B:发送其他类资源数据查询的请求
activate B
B   -> B:校验其他类资源数据查询请求头的合法性
activate C
B   -> C:从数据库中查询其他类资源数据信息
C --> B:返回其他类资源数据查询的结果信息

A   -> B:发送其他类资源数据详情查询的请求
B   -> B:校验其他类资源数据详情查询请求头的合法性
B   -> C:从数据库中查询其他类资源数据详情信息
C --> B:返回其他类资源数据保存草稿内容入库的结果信息

A   -> B:发送其他类资源数据保存草稿的请求
B   -> B:校验其他类资源数据保存草稿的请求头的合法性
B   -> C:把其他类资源数据保存草稿内容写入数据库
C --> B:返回其他类资源数据详情查询的结果信息

A   -> B:发送其他类资源数据提交审批的请求
B   -> B:校验其他类资源数据提交审批的请求头的合法性
B   -> C:把其他类资源数据提交审批内容写入数据库
C --> B:返回其他类资源数据提交审批内容入库的结果信息

B   --> A:返回其他类资源数据提交审批内容入库的结果信息
A   --> user:展示给用户相关信息
deactivate A
deactivate B
deactivate C

@enduml