
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2020-1-4';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2020-1-3';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2020-1-2';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2020-1-1';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-31';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-30';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-29';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-28';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-27';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-26';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-25';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-24';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-23';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-22';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-21';
insert into midata.mi_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date)SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.mi_visit_local_bak_1108`
 where ch_start_date='2019-12-20';


insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2020-1-4';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2020-1-3';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2020-1-2';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2020-1-1';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-31';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-30';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-29';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-28';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-27';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-26';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-25';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-24';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-23';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-22';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-21';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`
 where ch_start_date='2019-12-20';


insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2020-1-4';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2020-1-3';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2020-1-2';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2020-1-1';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-31';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-30';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-29';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-28';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-27';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-26';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-25';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-24';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-23';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-22';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-21';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-20';


insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2020-1-4';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2020-1-3';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2020-1-2';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2020-1-1';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-31';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-30';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-29';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-28';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-27';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-26';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-25';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-24';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-23';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-22';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-21';
insert into  midata.mi_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.mi_visit_agg_1m_local_bak_1108`
 where ch_start_date='2019-12-20';


insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2020-1-4'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2020-1-3'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2020-1-2'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2020-1-1'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-31'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-30'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-29'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-28'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-27'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-26'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-25'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-24'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-23'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-22'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-21'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;
insert into  midata.mi_customer_agg_1d_local (  customer_name ,  device_uuid ,  app_id ,  app_version_id ,  os_id ,  device_id ,  country_id ,  region_id ,  city_id ,  visit_count ,  action_count ,  http_count ,  http_error_count ,  crash_count ,  slow_count ,  latest_visit_time ,  earliest_visit_time ,  timestamp ,  ch_start_date  ) SELECT            customer_name,            device_uuid,            app_id,            app_version_id,            os_id,            device_id,            country_id,            region_id,            city_id,            uniqState(uuid) AS visit_count,            sumState(action_count) AS action_count,            sumState(http_count) AS http_count,            sumState(http_error_count) AS http_error_count,            sumState(crash_count) AS crash_count,            sumState(slow_count) AS slow_count,            maxState(latest_visit_time) AS latest_visit_time,            maxState(first_visit_time) AS earliest_visit_time,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-20'
GROUP BY app_id, customer_name, device_uuid, app_version_id, os_id, device_id, country_id, region_id, city_id, ch_start_date, timestamp;


insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2020-1-4'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2020-1-3'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2020-1-2'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2020-1-1'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-31'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-30'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-29'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-28'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-27'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-26'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-25'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-24'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-23'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-22'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-21'
GROUP BY app_id, ch_start_date, timestamp;
insert into  midata.mi_active_device_agg_1d_local (  app_id ,  device_count ,  timestamp ,  ch_start_date  ) SELECT            app_id,            uniqState(device_uuid) AS device_count,            toUInt64((intDiv(timestamp + ((60000 * 60) * 8), (60000 * 60) * 24) * ((60000 * 60) * 24)) - ((60000 * 60) * 8)) AS timestamp,            ch_start_date    FROM midata.mi_visit_local
 where ch_start_date='2019-12-20'
GROUP BY app_id, ch_start_date, timestamp;



