
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2020-1-4';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2020-1-3';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2020-1-2';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2020-1-1';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-31';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-30';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-29';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-28';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-27';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-26';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-25';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-24';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-23';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-22';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-21';
insert into midata.web_visit_local (uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date) SELECT uuid,app_id,app_version_id,agent_id,os_id,device_id,country_id,region_id,city_id,carrier_id,customer_name,device_uuid,visit_status,first_visit_time,latest_visit_time,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,timestamp,ch_start_date FROM midata.`.inner.web_visit_local_bak_1108`   
 where ch_start_date='2019-12-20';

