
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2020-1-4';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2020-1-3';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2020-1-2';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2020-1-1';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-31';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-30';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-29';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-28';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-27';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-26';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-25';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-24';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-23';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-22';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-21';
insert into midata.web_visit_agg_1m_local (app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count)SELECT app_id,app_version_id,os_id,device_id,country_id,region_id,city_id,carrier_id,ch_start_date,timestamp,visit_count,customer_count,device_uuid_count,action_count,http_count,http_error_count,crash_count,anr_count,slow_count,http_third_count FROM midata.`.inner.web_visit_agg_1m_local_bak_1108`   
 where ch_start_date='2019-12-20';

