drop table midata.mi_http_agg_customer_1m_local_1128;
drop table midata.web_http_agg_customer_1m_local_1128;
CREATE MATERIALIZED VIEW IF NOT EXISTS midata.mi_http_agg_customer_1m_local (
  app_id Int64,
  app_version_id Int64,
  os_id Int64,
  device_id Int64,
  country_id Int64,
  region_id Int64,
  city_id Int64,
  carrier_id Int64,
  initiator Int64,
  host String,
  path String,
  customer_name String,
  device_uuid String,
  status_code Int64,
  error_code Int64,
  is_self_owned Int64,
  ch_start_date Date,
  timestamp UInt64,
  duration AggregateFunction(sum, Int64),
  first_byte_duration AggregateFunction(sum, Int64),
  total_count AggregateFunction(sum, Int64),
  slow_count AggregateFunction(countIf, UInt8),
  bytes_sent AggregateFunction(sum, Int64),
  bytes_received AggregateFunction(sum, Int64),
  server_duration AggregateFunction(sum, Int64),
  total_count_with_server_duration AggregateFunction(countIf, UInt8)
  ) ENGINE = AggregatingMergeTree()
  PARTITION BY toYYYYMMDD(ch_start_date)
  order by (app_id, customer_name, device_uuid, timestamp, host, path, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, status_code, error_code, is_self_owned, initiator)
  SETTINGS index_granularity = 8192
  AS SELECT
            app_id,
            app_version_id,
            os_id,
            device_id,
            country_id,
            region_id,
            city_id,
            carrier_id,
            initiator,
            host,
            path,
            customer_name,
            device_uuid,
            status_code,
            error_code,
            is_self_owned,
            ch_start_date,
            toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,
            sumState(duration) AS duration,
            sumState(first_byte_duration) AS first_byte_duration,
            sumState(total_count) AS total_count,
            countIfState(is_slow > 0) AS slow_count,
            sumState(bytes_sent) AS bytes_sent,
            sumState(bytes_received) AS bytes_received,
            sumState(server_duration) AS server_duration,
            countIfState(server_guid != '') AS total_count_with_server_duration
  FROM midata.mi_http_insert
  GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;

  CREATE MATERIALIZED VIEW IF NOT EXISTS midata.web_http_agg_customer_1m_local (
  app_id Int64,
  app_version_id Int64,
  os_id Int64,
  device_id Int64,
  country_id Int64,
  region_id Int64,
  city_id Int64,
  carrier_id Int64,
  initiator Int64,
  host String,
  path String,
  method String,
  status_code Int64,
  error_code Int64,
  is_self_owned Int64,
  customer_name String,
  device_uuid String,
  ch_start_date Date,
  timestamp UInt64,
  duration AggregateFunction(sum, Int64),
  first_byte_duration AggregateFunction(sum, Int64),
  total_count AggregateFunction(sum, Int64),
  slow_count AggregateFunction(countIf, UInt8),
  bytes_sent AggregateFunction(sum, Int64),
  bytes_received AggregateFunction(sum, Int64),
  server_duration AggregateFunction(sum, Int64),
  total_count_with_server_duration AggregateFunction(countIf, UInt8)
  ) ENGINE = AggregatingMergeTree()
  PARTITION BY toYYYYMMDD(ch_start_date)
  order by (app_id, customer_name, device_uuid, is_self_owned, host, app_version_id, os_id, carrier_id, country_id, region_id, city_id, device_id, status_code, error_code, path, method)
  SETTINGS index_granularity = 8192
  AS SELECT
            app_id,
            app_version_id,
            os_id,
            device_id,
            country_id,
            region_id,
            city_id,
            carrier_id,
            initiator,
            host,
            path,
            method,
            status_code,
            error_code,
            is_self_owned,
            customer_name,
            device_uuid,
            ch_start_date,
            toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,
            sumState(duration) AS duration,
            sumState(first_byte_duration) AS first_byte_duration,
            sumState(total_count) AS total_count,
            countIfState(is_slow = 1) AS slow_count,
            sumState(bytes_sent) AS bytes_sent,
            sumState(bytes_received) AS bytes_received,
            sumState(server_duration) AS server_duration,
            countIfState(server_guid != '') AS total_count_with_server_duration
  FROM midata.web_http_insert
  GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;



insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2020-1-4'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2020-1-3'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2020-1-2'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2020-1-1'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-31'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-30'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-29'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-28'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-27'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-26'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-25'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-24'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-23'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-22'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-21'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;
insert into midata.mi_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    customer_name ,    device_uuid ,    status_code ,    error_code ,    is_self_owned ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      customer_name,      device_uuid,      status_code,      error_code,      is_self_owned,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow > 0) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.mi_http_local
 where ch_start_date='2019-12-20'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, initiator, host, path, customer_name, device_uuid, status_code, error_code, is_self_owned, ch_start_date, timestamp;


insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2020-1-4'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2020-1-3'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2020-1-2'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2020-1-1'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-31'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-30'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-29'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-28'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-27'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-26'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-25'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-24'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-23'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-22'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-21'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;
insert into midata.web_http_agg_customer_1m_local (    app_id ,    app_version_id ,    os_id ,    device_id ,    country_id ,    region_id ,    city_id ,    carrier_id ,    initiator ,    host ,    path ,    method ,    status_code ,    error_code ,    is_self_owned ,    customer_name ,    device_uuid ,    ch_start_date ,    timestamp ,    duration ,    first_byte_duration ,    total_count ,    slow_count ,    bytes_sent ,    bytes_received ,    server_duration ,    total_count_with_server_duration) SELECT      app_id,      app_version_id,      os_id,      device_id,      country_id,      region_id,      city_id,      carrier_id,      initiator,      host,      path,      method,      status_code,      error_code,      is_self_owned,      customer_name,      device_uuid,      ch_start_date,      toUInt64(intDiv(timestamp, 60000) * 60000) AS timestamp,      sumState(duration) AS duration,      sumState(first_byte_duration) AS first_byte_duration,      sumState(total_count) AS total_count,      countIfState(is_slow = 1) AS slow_count,      sumState(bytes_sent) AS bytes_sent,      sumState(bytes_received) AS bytes_received,      sumState(server_duration) AS server_duration,      countIfState(server_guid != '') AS total_count_with_server_duration FROM midata.web_http_local
 where ch_start_date='2019-12-20'
GROUP BY app_id, app_version_id, os_id, device_id, country_id, region_id, city_id, carrier_id, host, path, method, status_code, error_code, is_self_owned, initiator, customer_name, device_uuid, ch_start_date, timestamp;

