@startuml
title 	密钥生成接口改造

actor "用户使用browser/app"
participant "一级BOMC" as A
participant "数据库" as B

activate A

A   -> A:接收密钥生成接口
A   -> A:读取密钥生成接口请求信息

A   -> B :解析密钥生成接口client_ip信息入库
activate B
B   -> A:返回最终密钥生成接口信息的入库结果
@enduml