@startuml
title 	帐号角色关系发送接口改造

actor "用户使用browser/app"
participant "一级BOMC" as A
participant "数据库" as B

activate A

A   -> A:接收帐号角色关系发送接口
A   -> A:读取帐号角色关系发送接口请求信息

A   -> B :解析帐号角色关系发送接口client_ip信息入库
activate B
B   -> A:返回最终帐号角色关系发送接口信息的入库结果
@enduml