@startuml
title 	统一凭证校验接口改造时序图

actor "用户使用browser/app"
participant "一级BOMC" as A
participant "数据库" as B

activate A

A   -> A:接收统一凭证校验接口请求
A   -> A:读取统一凭证校验接口请求信息

A   -> B :解析统一凭证校验接口client_ip信息入库
activate B
B   -> A:返回最终统一凭证校验接口信息的入库结果
@enduml