@startuml
title 	角色变更改造

actor "用户使用browser/app"
participant "一级BOMC" as A
participant "数据库" as B

activate A

A   -> A:接收角色变更改造
A   -> A:读取角色变更改造请求信息

A   -> B :解析角色变更改造client_ip信息入库
activate B
B   -> A:返回最终角色变更改造信息的入库结果
@enduml