@startuml
title 	请求密钥验证接口改造时序图

actor "用户使用browser/app"
participant "一级BOMC" as A
participant "数据库" as B
participant "4a平台" as C

activate A

A   -> A:接收请求密钥验证接口改造请求

A   -> B:读取请求密钥验证接口改造数据库中client_ip
activate B
B   -> A:返回client_ip
A   -> A:存放到请求的header中

A   -> C :调用请求密钥验证接口改造
activate C
C   -> A :返回最终请求密钥验证接口改造信息的入库结果
@enduml